/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GuiFormulario;

import Dto.EntidadDto;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author carlos
 */
public class GuiConsultarEntidad extends javax.swing.JFrame {

    private GuiMenu menu;

    /**
     * Creates new form GuiConsultarEntidad
     */
    public GuiConsultarEntidad(GuiMenu menu) {
        initComponents();
        this.menu = menu;
        this.btnActualizar.setBackground(Color.white);

    }

    public void cargarTabla() {

        ArrayList<EntidadDto> cad=this.menu.getPrincipal().getFachada().consultarEntidades();
        String[] nomC = new String[5];
        nomC[0] = "Codigo";
        nomC[1] = "Nombre";
        nomC[2] = "Sufijo";
        nomC[3] = "Direccion";
        nomC[4] = "Telefono";

        String datos[][] = new String[cad.size()][5];
        for (int i = 0; i < cad.size(); i++) {
            datos[i][0]=cad.get(i).getCodigo_entidad();
            datos[i][1]=cad.get(i).getNombre_entidad();
            datos[i][2]=cad.get(i).getSufijo();
            datos[i][3]=cad.get(i).getDireccion();
            datos[i][4]=cad.get(i).getTelefono();
            }
           this.TableEntidad.setModel(new DefaultTableModel(datos, nomC));
        }
     
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableEntidad = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        labelRegresar = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        TableEntidad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TableEntidad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableEntidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableEntidadMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableEntidad);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Entidades registradas en el sistema");

        labelRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/regresar.jpg"))); // NOI18N
        labelRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelRegresarMouseClicked(evt);
            }
        });

        btnActualizar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnActualizar.setText("Actualizar tabla");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(421, 421, 421))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(labelRegresar)
                .addGap(66, 66, 66)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        labelRegresar.getAccessibleContext().setAccessibleDescription("regresar al menu");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "debe cerrar sesion");
    }//GEN-LAST:event_formWindowClosing

    private void TableEntidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableEntidadMouseClicked
        // TODO add your handling code here:
        String[] datos = this.valorTabla();
        int codigo = Integer.parseInt(datos[0]);
        int seleccion = JOptionPane.showOptionDialog(
                rootPane,
                "Seleccione opcion a realizar para la entidad: " + codigo,
                "Selector de opciones ",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                new Object[]{"Modifircar", "   Borrar", "Cancelar"},
                "opcion 1");

        if (seleccion == 0) {

            GuiModificarEntidad modif = new GuiModificarEntidad(this.menu, codigo + "", datos[1], datos[2], datos[3], datos[4]);
            this.menu.getPrincipal().personalizar(modif);
            this.setVisible(false);
            modif.setVisible(true);
            return;
        }
        if (seleccion == 1) {
            boolean confirmacion = this.cerrar();
            if (confirmacion) {

                boolean x = this.menu.getPrincipal().getFachada().borrarEntidad(codigo);
                if (x) {
                    JOptionPane.showMessageDialog(null, "el registro se borro con exito");
                    this.cargarTabla();
                } else {
                    JOptionPane.showMessageDialog(null, "la entidad no se puede borrar \n"
                            + "tiene bonos asociados");
                }
            } else {
                return;
            }

        }

    }//GEN-LAST:event_TableEntidadMouseClicked

    private void labelRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRegresarMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        this.menu.setVisible(true);
    }//GEN-LAST:event_labelRegresarMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        this.cargarTabla();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private boolean cerrar() {
        Object[] opciones = {"Aceptar", "Cancelar"};
        int eleccion = JOptionPane.showOptionDialog(rootPane, "Esta seguro que desea borrar la entidad. ", "Mensaje de Confirmacion",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, opciones, "Cancelar");

        return (eleccion == JOptionPane.YES_OPTION);

    }

    private String[] valorTabla() {

        if (this.TableEntidad.getSelectedRow() >= 0) {

            String datos[] = {
                String.valueOf(this.TableEntidad.getValueAt(this.TableEntidad.getSelectedRow(), 0)),
                String.valueOf(this.TableEntidad.getValueAt(this.TableEntidad.getSelectedRow(), 1)),
                String.valueOf(this.TableEntidad.getValueAt(this.TableEntidad.getSelectedRow(), 2)),
                String.valueOf(this.TableEntidad.getValueAt(this.TableEntidad.getSelectedRow(), 3)),
                String.valueOf(this.TableEntidad.getValueAt(this.TableEntidad.getSelectedRow(), 4))
            };

            return datos;
        }
        return null;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableEntidad;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelRegresar;
    // End of variables declaration//GEN-END:variables
}
