/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GuiFormulario;

import GuiPrincipal.GuiPrincipal;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author carlos
 */
public class GuiMenu extends javax.swing.JFrame {

    private GuiPrincipal principal;
    public String usuario;
    public String Nuip;
    private GuiConsultarEnrolarBono ConsultarEnrolarBono;
    private GuiConsultarEntidad consultarEntidad;
    private GuiCrearEnrolarBono crearEnrolarBono;
    private GuiCrearEntidad crearEntidad;
    private GuiModificarEntidad modificarEntidad;
    private GuiPagarBono pagarBono;
    private GuiReporte repote;

    public String tipo;

    /**
     * Creates new form GuiMenu
     */
    public GuiMenu(GuiPrincipal principal, String usuario, String Nuip, String tipo) {
        this.tipo = tipo;
        this.principal = principal;
        this.usuario = usuario;
        this.Nuip = Nuip;
        initComponents();
        this.personalizarComponentes();
    }

    public GuiPrincipal getPrincipal() {
        return principal;
    }

    /**
     * da color a los paneles
     */
    private void personalizarComponentes() {
        this.setTitle("Usuario " + usuario);
        this.PanelEntidades.setBackground(Color.white);
        this.PanelEnrolarBono.setBackground(Color.white);
        this.PanelPagarBono.setBackground(Color.white);
        this.PanelReporte.setBackground(Color.white);
        this.btnConsultaEnrolarBono.setBackground(Color.white);
        this.btnCreacionEntidad.setBackground(Color.white);
        this.btnConsultaEntidad.setBackground(Color.white);
        this.btnCreacionEnrolarBono.setBackground(Color.white);
        this.btnPagoBono.setBackground(Color.white);
        this.btnGenerarReporte.setBackground(Color.white);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelEntidades = new javax.swing.JPanel();
        btnCreacionEntidad = new javax.swing.JButton();
        btnConsultaEntidad = new javax.swing.JButton();
        PanelReporte = new javax.swing.JPanel();
        btnGenerarReporte = new javax.swing.JButton();
        PanelEnrolarBono = new javax.swing.JPanel();
        btnCreacionEnrolarBono = new javax.swing.JButton();
        btnConsultaEnrolarBono = new javax.swing.JButton();
        PanelPagarBono = new javax.swing.JPanel();
        btnPagoBono = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuItemCerrarSesion1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Menu");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        PanelEntidades.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Entidades", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        btnCreacionEntidad.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCreacionEntidad.setText("Creacion Entidad");
        btnCreacionEntidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreacionEntidadActionPerformed(evt);
            }
        });

        btnConsultaEntidad.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnConsultaEntidad.setText("Consulta Entidad");
        btnConsultaEntidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaEntidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelEntidadesLayout = new javax.swing.GroupLayout(PanelEntidades);
        PanelEntidades.setLayout(PanelEntidadesLayout);
        PanelEntidadesLayout.setHorizontalGroup(
            PanelEntidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEntidadesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCreacionEntidad, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(PanelEntidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelEntidadesLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnConsultaEntidad, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        PanelEntidadesLayout.setVerticalGroup(
            PanelEntidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEntidadesLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnCreacionEntidad)
                .addContainerGap(121, Short.MAX_VALUE))
            .addGroup(PanelEntidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEntidadesLayout.createSequentialGroup()
                    .addContainerGap(98, Short.MAX_VALUE)
                    .addComponent(btnConsultaEntidad)
                    .addGap(45, 45, 45)))
        );

        PanelReporte.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Reporte", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        btnGenerarReporte.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnGenerarReporte.setText("Generar Reportes");
        btnGenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelReporteLayout = new javax.swing.GroupLayout(PanelReporte);
        PanelReporte.setLayout(PanelReporteLayout);
        PanelReporteLayout.setHorizontalGroup(
            PanelReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelReporteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGenerarReporte, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelReporteLayout.setVerticalGroup(
            PanelReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelReporteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGenerarReporte)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        PanelEnrolarBono.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Enrolar Bono", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        btnCreacionEnrolarBono.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCreacionEnrolarBono.setText("Creacion Enrolar Bono");
        btnCreacionEnrolarBono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreacionEnrolarBonoActionPerformed(evt);
            }
        });

        btnConsultaEnrolarBono.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnConsultaEnrolarBono.setText("Consulta Enrolar Bono");
        btnConsultaEnrolarBono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaEnrolarBonoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelEnrolarBonoLayout = new javax.swing.GroupLayout(PanelEnrolarBono);
        PanelEnrolarBono.setLayout(PanelEnrolarBonoLayout);
        PanelEnrolarBonoLayout.setHorizontalGroup(
            PanelEnrolarBonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEnrolarBonoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelEnrolarBonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCreacionEnrolarBono, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addComponent(btnConsultaEnrolarBono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelEnrolarBonoLayout.setVerticalGroup(
            PanelEnrolarBonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEnrolarBonoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnCreacionEnrolarBono)
                .addGap(45, 45, 45)
                .addComponent(btnConsultaEnrolarBono)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelPagarBono.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Pagar Bono", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        btnPagoBono.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnPagoBono.setText("Pago De Bonos");
        btnPagoBono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagoBonoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPagarBonoLayout = new javax.swing.GroupLayout(PanelPagarBono);
        PanelPagarBono.setLayout(PanelPagarBonoLayout);
        PanelPagarBonoLayout.setHorizontalGroup(
            PanelPagarBonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPagarBonoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPagoBono, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelPagarBonoLayout.setVerticalGroup(
            PanelPagarBonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPagarBonoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPagoBono)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        jMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/usuario.jpg"))); // NOI18N
        jMenu1.setText("BIENVENIDO");
        jMenu1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        MenuItemCerrarSesion1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        MenuItemCerrarSesion1.setText("Cerrar Sesion");
        MenuItemCerrarSesion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemCerrarSesion1ActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemCerrarSesion1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelEntidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelPagarBono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(PanelEnrolarBono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(PanelReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelEntidades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelEnrolarBono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelPagarBono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarReporteActionPerformed
        // TODO add your handling code here:
        if (this.repote == null) {
            this.repote = new GuiReporte(this);
            this.repote.setTitle(this.getTitle());
            this.principal.personalizar(this.repote);
        }

        this.setVisible(false);
        this.repote.setVisible(true);

    }//GEN-LAST:event_btnGenerarReporteActionPerformed

    private void btnPagoBonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagoBonoActionPerformed
        // TODO add your handling code here:

        this.mostrarPagoBono();
    }//GEN-LAST:event_btnPagoBonoActionPerformed

    public void mostrarMenu() {
        if (this.tipo.equals("1")) {

            this.setVisible(true);
            return;
        }

        this.mostrarPagoBono();
    }

    private void mostrarPagoBono() {
        if (this.pagarBono == null) {
            this.pagarBono = new GuiPagarBono(this);
            this.pagarBono.setTitle(this.getTitle());
            this.principal.personalizar(this.pagarBono);
        }
        this.pagarBono.limpiarCamposBono();
        this.setVisible(false);
        this.pagarBono.setVisible(true);
    }

    private void btnConsultaEntidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaEntidadActionPerformed
        // TODO add your handling code here:
        if (this.consultarEntidad == null) {
            this.consultarEntidad = new GuiConsultarEntidad(this);
            this.consultarEntidad.setTitle(this.getTitle());
            this.principal.personalizar(this.consultarEntidad);
        }
        this.consultarEntidad.cargarTabla();
        this.setVisible(false);
        this.consultarEntidad.setVisible(true);
    }//GEN-LAST:event_btnConsultaEntidadActionPerformed

    private void btnCreacionEntidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreacionEntidadActionPerformed
        // TODO add your handling code here:
        if (this.crearEntidad == null) {
            this.crearEntidad = new GuiCrearEntidad(this);
            this.crearEntidad.setTitle(this.getTitle());
            this.principal.personalizar(this.crearEntidad);
        }

        this.setVisible(false);
        this.crearEntidad.setVisible(true);

    }//GEN-LAST:event_btnCreacionEntidadActionPerformed

    private void btnCreacionEnrolarBonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreacionEnrolarBonoActionPerformed
        // TODO add your handling code here:
        if (this.crearEnrolarBono == null) {
            this.crearEnrolarBono = new GuiCrearEnrolarBono(this);
            this.crearEnrolarBono.setTitle(this.getTitle());
            this.principal.personalizar(this.crearEnrolarBono);
        }
        this.crearEnrolarBono.cargarComponentes();
        this.setVisible(false);
        this.crearEnrolarBono.setVisible(true);

    }//GEN-LAST:event_btnCreacionEnrolarBonoActionPerformed

    private void btnConsultaEnrolarBonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaEnrolarBonoActionPerformed
        // TODO add your handling code here:
        if (this.ConsultarEnrolarBono == null) {
            this.ConsultarEnrolarBono = new GuiConsultarEnrolarBono(this);
            this.ConsultarEnrolarBono.setTitle(this.getTitle());
            this.principal.personalizar(this.ConsultarEnrolarBono);
        }
        this.ConsultarEnrolarBono.cargarTabla();

        this.setVisible(false);
        this.ConsultarEnrolarBono.setVisible(true);
    }//GEN-LAST:event_btnConsultaEnrolarBonoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "debe cerrar sesion");
    }//GEN-LAST:event_formWindowClosing

    private void MenuItemCerrarSesion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemCerrarSesion1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.principal.setVisible(true);
    }//GEN-LAST:event_MenuItemCerrarSesion1ActionPerformed

    public GuiConsultarEnrolarBono getConsultarEnrolarBono() {
        return ConsultarEnrolarBono;
    }

    public GuiConsultarEntidad getConsultarEntidad() {
        return consultarEntidad;
    }

    public GuiCrearEnrolarBono getCrearEnrolarBono() {
        return crearEnrolarBono;
    }

    public GuiCrearEntidad getCrearEntidad() {
        return crearEntidad;
    }

    public GuiModificarEntidad getModificarEntidad() {
        return modificarEntidad;
    }

    public GuiPagarBono getPagarBono() {
        return pagarBono;
    }

    public void setPagarBono(GuiPagarBono pBono) {
        this.pagarBono = pBono;
    }

    public GuiReporte getReporte() {
        return this.repote;
    }

    public void setReporte(GuiReporte reporte) {
        this.repote = reporte;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuItemCerrarSesion1;
    private javax.swing.JPanel PanelEnrolarBono;
    private javax.swing.JPanel PanelEntidades;
    private javax.swing.JPanel PanelPagarBono;
    private javax.swing.JPanel PanelReporte;
    private javax.swing.JButton btnConsultaEnrolarBono;
    private javax.swing.JButton btnConsultaEntidad;
    private javax.swing.JButton btnCreacionEnrolarBono;
    private javax.swing.JButton btnCreacionEntidad;
    private javax.swing.JButton btnGenerarReporte;
    private javax.swing.JButton btnPagoBono;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
